// Build-time media asset lookup.
// SVGs are imported via import.meta.glob (URL strings).
// Raster images are pre-optimized by scripts/optimize-media.mjs into
// public/media/{id}.jpg and public/media/{id}.webp — dimensions are
// read from the accompanying manifest .optimized-manifest.json.
//
// This avoids eager-importing raster files (which duplicated them into
// dist/_astro/ at original size) while still providing accurate metadata.

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getCollection } from 'astro:content';
import type { MediaEntry } from '../content/config';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PROJECT_ROOT = resolve(__dirname, '..', '..');

/** SVG files — imported as URL strings */
const svgModules = import.meta.glob<string>(
  '/src/content/media/*.svg',
  { eager: true, query: '?url', import: 'default' }
);

/** Resolved media entry paired with its optimized file metadata */
export interface ResolvedMedia extends MediaEntry {
  src: string;
  width: number;
  height: number;
  format: string;
}

/** Extract filename stem (without dir or extension) */
function pathStem(filePath: string): string {
  return filePath.split('/').pop()!.replace(/\.\w+$/, '');
}

/** Read the optimized-dimensions manifest produced by scripts/optimize-media.mjs */
function readOptimizedManifest(): Record<string, { width: number; height: number }> {
  const manifestPath = resolve(PROJECT_ROOT, 'public/media/.optimized-manifest.json');
  if (!existsSync(manifestPath)) {
    // During dev / first build the manifest may not exist yet; return empty.
    return {};
  }
  try {
    return JSON.parse(readFileSync(manifestPath, 'utf-8'));
  } catch {
    return {};
  }
}

/** Get a resolved media entry by ID — async */
export async function getMedia(id: string): Promise<ResolvedMedia | undefined> {
  const all = await getAllMedia();
  return all.find((m) => m.id === id);
}

/** Get all resolved media entries — async */
export async function getAllMedia(): Promise<ResolvedMedia[]> {
  const entries = await getCollection('media');
  const byId = new Map<string, MediaEntry>();
  for (const e of entries) {
    byId.set(e.id, e.data as MediaEntry);
  }

  const optManifest = readOptimizedManifest();
  const resolved: ResolvedMedia[] = [];

  // ── SVGs ──
  for (const [filePath, url] of Object.entries(svgModules)) {
    const stem = pathStem(filePath);
    const entry = byId.get(stem);
    if (entry) {
      resolved.push({
        ...entry,
        src: url,
        width: entry.width ?? 800,
        height: entry.height ?? 600,
        format: 'svg',
      });
    }
  }

  // ── Raster images (pre-optimized) ──
  // These live in public/media/ as {id}.jpg (fallback) + {id}.webp (modern).
  // We do NOT import them via import.meta.glob — that created 536 MB of
  // duplicate hashed copies in dist/_astro/. Instead, we read dimensions
  // from the build-manifest generated by scripts/optimize-media.mjs.
  for (const [id, entry] of byId) {
    // Skip SVGs — already handled above
    if (entry.format === 'svg') continue;
    // Skip if no optimized manifest entry (media JSON exists but no image file)
    const dims = optManifest[id] || { width: entry.width ?? 800, height: entry.height ?? 600 };
    resolved.push({
      ...entry,
      src: `/media/${id}.jpg`,
      width: dims.width,
      height: dims.height,
      format: 'jpg',
    });
  }

  return resolved;
}
