/**
 * widgets.ts — Registry of non-map interactive embeddable components.
 *
 * Unlike maps (which are Leaflet-based and need separate script initialization),
 * widgets are pure HTML+CSS components that can be fully generated at build time
 * by the remark-figure-embed plugin via `[widget:id]` markers.
 *
 * Convention: add every non-map interactive widget here.
 * The ID is used as the `[widget:id]` marker in markdown.
 */

export interface WidgetRegistryEntry {
  id: string;
  /** If true, the remark plugin's buildWidgetFigure generates the HTML. */
  isBuildTime: boolean;
}

export const WIDGET_REGISTRY: Record<string, WidgetRegistryEntry> = {
  'revolution-bilan': {
    id: 'revolution-bilan',
    isBuildTime: false, // Generated by RevolutionBilan.astro as a conditional component
  },
};
